language: objective-c
env:
  - TI_SDK=3.3.0.GA
script:
  - titanium info
before_install:
  - xcode-select -print-path
  - npm install --global titanium
  - mkdir -p $HOME/.titanium
  - cp auth_session.json $HOME/.titanium/auth_session.json
  - titanium sdk install "$TI_SDK"
