language: objective-c
env:
  - TI_SDK=3.4.0.GA IOS_VERSION=7.1
script:
  - titanium info
before_install:
  - xcode-select -print-path
  - npm install --global titanium
  - mkdir -p $HOME/.titanium
  - cp auth_session.json $HOME/.titanium/auth_session.json
  - titanium sdk install "$TI_SDK"
  - cd app
  - titanium build --build-only --platform ios --ios-version $IOS_VERSION
