language: objective-c
env:
  - TI_SDK=3.4.0.GA IOS_VERSION=8.0
script:
  - cd app
  - titanium --no-progress-bars --no-prompt --no-banner build --build-only --platform ios --ios-version $IOS_VERSION
before_install:
  - npm install --global titanium
  - mkdir -p $HOME/.titanium
  - cp auth_session.json $HOME/.titanium/auth_session.json
  - titanium --no-progress-bars --no-prompt --no-banner sdk install "$TI_SDK"
